### ISSUE TITLE
Website.Detail.About.Link to Astartup Cookbook for Session ticket instructions; Website.Blog.2019-12-9.Backdate.

### ISSUE THREAD

**Issue by kabuki-starship** [kabuki-starship/cooking_with_cale#9]
# Getting up to speed

## Problem

People don't know how to read session tickets because they're not psychic.

## Solution

Add a page for how to read session tickets that links to the Astartup Cookbook.

## Hierarchy

* #8

**Comment by CookingWithCale** [comment]
`>Session.Ticket.Bounce Website.Detail.About.Link to AStartup Cookbook for Session ticket instructions; Website.Blog.2019-12-9.Backdate.<`
